config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'pages#home'

  resources :conversations, only: %i[show new create update index] do
    get :unread, on: :collection
  end

  resources :feedbacks, only: %i[show new create edit update destroy index]

  resources :itineraries, only: %i[show new create edit update destroy index search] do
    post :search, on: :collection
    resources :build
  end

  resources :users, only: %i[show update destroy] do
    get :itineraries, on: :member
  end

  # Admin Area
  namespace :admin do
    resources :users, only: [:index] do
      get :login_as, on: :member
      post :ban, :unban, on: :member
    end
  end

  # Root route aliases
  get :dashboard, to: 'users#dashboard'
  get :settings, to: 'users#settings'
  get :banned, to: 'users#banned'

  get :about, to: 'pages#about'
  get :how_it_works, to: 'pages#how_it_works'
  get :privacy, to: 'pages#privacy'
  get :terms, to: 'pages#terms'
  get :demo_terms, to: 'pages#demo_terms'
  post :report_uri, to: 'pages#report_uri'
end

app/models/itineraries/search.rb
# frozen_string_literal: true

module Itineraries
  class Search
    include ::ActiveModel::Model

    attr_accessor :from, :to,
                  :start_location_lat, :start_location_lng, :end_location_lat, :end_location_lng,
                  :filter_round_trip, :filter_pink, :filter_smoking_allowed, :filter_pets_allowed, :filter_driver_gender

    validates :from, presence: true
    validates :to, presence: true
  end
end

app/models/itinerary.rb
# frozen_string_literal: true

class Itinerary < ApplicationRecord
  include GeoItinerary
  extend FriendlyId

  DAYNAME = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday].freeze

  friendly_id :name, use: :slugged

  def name
    [start_address, end_address].join ' '
  end

  has_many :conversations, as: :conversable, dependent: :destroy

  belongs_to :user
  delegate :name, to: :user, prefix: true
  delegate :first_name, to: :user, prefix: true

  validates :description, length: { maximum: 1000 }, presence: true
  validates :num_people, numericality: { only_integer: true, greater_than: 0, less_than: 10 }, allow_blank: true
  validates :fuel_cost, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 10_000 }
  validates :tolls, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 10_000 }
  validates :leave_date, timeliness: { on_or_after: -> { Time.current } }, on: :create
  validates :return_date, presence: true, if: -> { round_trip }

  validate :driver_is_female, if: -> { pink }
  validate :return_date_validator, if: -> { round_trip }

  def return_date_validator
    return unless return_date && return_date <= leave_date

    errors.add(:return_date,
               I18n.t('mongoid.errors.messages.after',
                      restriction: leave_date.strftime(I18n.t('validates_timeliness.error_value_formats.datetime'))))
  end

  def driver_is_female
    errors.add(:pink, :driver_must_be_female) unless user.female?
  end

  before_create do
    self.driver_gender = user.gender
    true
  end

  def title
    [start_address, end_address].join ' - '
  end

  def to_s
    title || id
  end
end

app/controllers/itineraries_controller.rb
# frozen_string_literal: true

class ItinerariesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  before_action :set_itinerary, only: [:show]
  before_action :check_female, only: [:show]

  before_action :check_permissions

  def new
    @itinerary = Itinerary.new
  end

  def index
    # @itineraries = Itinerary.includes(:user).all
  end

  def show
    @conversation = @itinerary.conversations.find_or_initialize_by(sender: current_user, receiver: @itinerary.user) if current_user
    session[:redirect_to] = itinerary_path(@itinerary) unless user_signed_in?
  end

  def create
    @itinerary = current_user.itineraries.new(itinerary_params)
    if @itinerary.save
      redirect_to itinerary_path(@itinerary), flash: { success: t('flash.itineraries.success.create') }
    else
      render :new
    end
  end

  def edit
    @itinerary = current_user.itineraries.friendly.find params[:id]
  end

  def update
    @itinerary = current_user.itineraries.friendly.find params[:id]
    if @itinerary.update itinerary_params
      redirect_to itinerary_path(@itinerary), flash: { success: t('flash.itineraries.success.update') }
    else
      render :edit
    end
  end

  def destroy
    @itinerary = current_user.itineraries.friendly.find params[:id]
    @itinerary.destroy
    redirect_to itineraries_user_path(current_user), flash: { success: t('flash.itineraries.success.destroy') }
  end

  def search
    @itineraries = ItinerarySearch.new(params[:itineraries_search], current_user).itineraries
  end

  protected

  def check_permissions; end

  def set_itinerary
    @itinerary = Itinerary.friendly.find params[:id]
  end

  def itinerary_params
    params.require(:itinerary).permit(*itinerary_attributes)
  end

  def itinerary_attributes
    whitelist = %i[start_address end_address description num_people smoking_allowed pets_allowed fuel_cost tolls
                   avoid_highways avoid_tolls
                   round_trip leave_date return_date daily
                   route]
    whitelist << :pink if current_user&.female?
    whitelist
  end

  def check_female
    return unless @itinerary.pink?

    if !user_signed_in?
      redirect_to root_path
    elsif !current_user.female?
      redirect_to :dashboard, flash: { error: t('flash.itineraries.error.pink') }
    end
  end
end

app/helpers/itineraries_helper.rb
# frozen_string_literal: true

module ItinerariesHelper
  def boolean_options_for_select
    @boolean_options_for_select ||= [[t('boolean.true'), true], [t('boolean.false'), false]]
  end

  def default_leave_date
    @default_leave_date ||= Time.current.change(min: (Time.current.min / 10) * 10) + 10.minutes
  end

  def boolean_tag(value, field)
    status = value ? 'allowed' : 'forbidden'

    tag.div class: "tag tag-#{status}" do
      concat tag.span(nil, class: "fas fa-#{status == 'allowed' ? 'check' : 'ban'}")
      concat ' '
      concat t(".#{field}.#{status}")
    end
  end
end

app/views/itineraries/_form.html.slim
fieldset#single
  = f.input :leave_date, as: :datetime, default: default_leave_date, start_year: Time.current.year, end_year: 1.year.from_now.year, minute_step: 10, ampm: t('time.ampm'), input_html: { class: 'date-time' }, wrapper: :horizontal_form
  = f.input :round_trip, as: :boolean, wrapper: :horizontal_boolean
  = f.input :return_date, as: :datetime, default: default_leave_date, start_year: Time.current.year, end_year: 1.year.from_now.year, minute_step: 10, ampm: t('time.ampm'), input_html: { class: 'date-time' }, disabled: !@itinerary.round_trip, wrapper: :horizontal_form
  = f.input :fuel_cost, wrapper: :horizontal_form do
    .input-group.text-right
      = f.text_field :fuel_cost, class: 'form-control text-right'
      .input-group-append
        span.input-group-text = APP_CONFIG.currency
    p.form-text.text-muted.mb-0#fuel-help data-avg-consumption=current_user.vehicle_avg_consumption
      small#fuel-help-text
  = f.input :tolls, wrapper: :horizontal_form do
    .input-group
      = f.text_field :tolls, class: 'form-control text-right'
      .input-group-append
        span.input-group-text = APP_CONFIG.currency
    - if @itinerary.errors.include?(:tolls)
      span.help-inline
        = @itinerary.errors.messages[:tolls].join(', ')
  = f.input :description, as: :text, input_html: { rows: 5 }, hint: t('.description_hint'), wrapper: :horizontal_form
  .form-group.row
    .col-sm-9.offset-sm-3
      - if current_user.female?
        = f.input :pink, as: :boolean, hint: t('.pink_hint'), wrapper: false
      = f.input :smoking_allowed, as: :boolean, wrapper: false
      = f.input :pets_allowed, as: :boolean, wrapper: false

/
  fieldset#daily.hide.mock
    .control-group
      .controls
        table.table.table-condensed.daily-itinerary-table
          thead
            tr
              th
              th= t('.day')
              th= t('.leave_time')
              th= t('.return_time')
          tbody
            - (0..6).each_with_index do |index|
              tr
                td
                  p.text-center
                    = check_box_tag "day-#{index}"
                td= label_tag "day-# index ", t('date.day_names')[index]
                td
                  = time_select 'one', 'two', { minute_step: 10, default: { hour: 8 }, ampm: t('time.ampm') }, class: 'date-time', disabled: (index > 0)
                td
                  = time_select 'one', 'two', { minute_step: 10, default: { hour: 18 }, ampm: t('time.ampm') }, class: 'date-time', disabled: (index > 0)
          tfoot
            tr
              td colspan="2"
              td colspan="2"
                = label_tag 'edit-all-times', class: 'checkbox inline' do
                  = check_box_tag 'edit-all-times', nil, checked: true
                  = t('.edit_all_times')

/
  .control-group.hide
    .controls
      = label_tag nil, class: 'radio inline' do
        = f.input, :daily, false, as: :radio, checked: true
        = t('.single_itinerary')
      | &nbsp;
      = label_tag nil, class: 'radio inline mock' do
        = f.default_tag :radio_button, :daily, true, class: 'inline'
        = t('.daily_itinerary')

app/views/itineraries/_header.html.slim
.page-header
  h1 = @itinerary.title
.row.itinerary-header.mb-2
  .col-sm-6
    = image_tag @itinerary.static_map, class: 'google-static-map img-fluid', alt: ''
  .col-sm-6
    .media
      = link_to user_path(@itinerary.user), class: 'mr-2' do
        = user_profile_picture @itinerary.user, style: 'media-object'
      .media-body
        h5.m-0
          - if user_signed_in?
            = link_to @itinerary.user, user_path(@itinerary.user)
          - else
            = t('.app_user', appname: APP_CONFIG.app_name)
        p.pre-line = @itinerary.description
    .tag-list
      span.tag.tag-icare = Itinerary.human_attribute_name :start_address
      span.tag = @itinerary.start_address
    .tag-list
      span.tag.tag-icare = Itinerary.human_attribute_name :end_address
      span.tag = @itinerary.end_address
    - unless @itinerary.daily?
      .tag-list
        span.tag.tag-icare = Itinerary.human_attribute_name :leave_date
        span.tag = l(@itinerary.leave_date, format: :long)
      - if @itinerary.round_trip?
        .tag-list
          span.tag.tag-icare = Itinerary.human_attribute_name :return_date
          span.tag = l(@itinerary.return_date, format: :long)
    .tag-list
      span.tag.tag-icare = t('.expenses_to_share')
      span.tag #{Itinerary.human_attribute_name(:fuel_cost)}: #{@itinerary.fuel_cost}#{APP_CONFIG.currency}
      span.tag #{Itinerary.human_attribute_name(:tolls)}: #{@itinerary.tolls}#{APP_CONFIG.currency}
    .tag-list
      - if @itinerary.pink?
        span.tag.tag-pink data-toggle='tooltip' title=t('itineraries.form.pink_hint')
          span.fas.fa-lock<>
          = Itinerary.human_attribute_name(:pink)
      = boolean_tag @itinerary.smoking_allowed?, 'smoking'
      = boolean_tag @itinerary.pets_allowed?, 'pets'

app/views/itineraries/_opengraph_head_contents.html.slim
- content_for :head do
  meta property='og:url' content=itinerary_url(itinerary)
  meta property='og:site_name' content=APP_CONFIG.app_name
  meta property='og:title' content=itinerary.title
  meta property='og:image' content=itinerary.static_map
  meta property='og:description' content=itinerary.description

app/views/itineraries/_route_step.html.slim
.row
  .col-sm-4
    = f.input :start_address
    = f.input :end_address
    = f.input :avoid_highways, as: :boolean
    = f.input :avoid_tolls, as: :boolean
    .form-group
      .d-flex.align-items-center
        = f.button :button, t('.get_route'), class: 'btn-primary', type: 'button', id: 'get-route'
        .spinner-border.text-primary.ml-2.itineraries-spinner#itineraries-spinner-j role='status'
          span.sr-only = t('loading')
    #map-error-j.d-none-soft.alert.alert-danger
    #map-result-j.d-none-soft.alert.alert-info
      = t('.distance')
      b#distance<
      br
      = t('.duration')
      b#duration<
  .col-sm-8
    .embed-responsive.embed-responsive-16by9.google-maps
      .embed-responsive-item#new-itinerary-map *map_config_attributes
    p#route-helper.d-none-soft
      small
        = Itinerary.human_attribute_name :start_location
        b#from-helper
        br
        = Itinerary.human_attribute_name :end_location
        b#to-helper
        br
        span#copyrights
.row
  .col-sm-4
    h3
      span.fas.fa-user-secret<>
      = t('.hint_privacy_title')
    p
      = t('.hint_privacy_content')
  .col-sm-4
    h3
      span.fas.fa-wrench<>
      = t('.hint_customize_title')
    p
      = t('.hint_customize_content')
  .col-sm-4
    h3
      span.fas.fa-search<>
      = t('.hint_search_before_title')
    p
      = t('.hint_search_before_content_html', search_link: (link_to t('.search_link'), itineraries_path))

app/views/itineraries/_search.html.slim
= simple_form_for Itineraries::Search.new, url: search_itineraries_path, method: :post, validate: true, remote: true do |f|
  = f.input :from, label: Itinerary.human_attribute_name(:start_address)
  = f.input :to, label: Itinerary.human_attribute_name(:end_address)
  a.collapse-link.collapsed role='button' data-toggle='collapse' href='#search-form-advanced-j' aria-expanded='false' aria-controls='search-form-advanced-j'
    span.fas.fa-chevron-down.icon--collapse<> aria-hidden='true'
    = t('.advanced_search')
  #search-form-advanced-j.search-form-advanced.collapse role='navigation'
    - if current_user.female?
      = f.input :filter_pink, as: :boolean, label: Itinerary.human_attribute_name(:pink), hint: t('itineraries.form.pink_hint'), wrapper_class: 'form-group form-group-sm'
    .form-group.form-group-sm
      = f.input :filter_round_trip, as: :boolean, label: Itinerary.human_attribute_name(:round_trip), wrapper: false
    - %i[smoking_allowed pets_allowed].each do |boolean_field|
      = f.input "filter_#{boolean_field}".to_sym, collection: boolean_options_for_select, include_blank: true, label: Itinerary.human_attribute_name(boolean_field), wrapper_class: 'form-group form-group-sm'
    = f.input :filter_driver_gender, collection: options_for_array_collection(User, :gender), include_blank: true, label: Itinerary.human_attribute_name(:driver_gender), wrapper_class: 'form-group form-group-sm'
  .form-group
    = f.hidden_field :start_location_lat
    = f.hidden_field :start_location_lng
    = f.hidden_field :end_location_lat
    = f.hidden_field :end_location_lng
    .d-flex.align-items-center
      = f.button :button, t('.search'), class: 'btn-primary', id: 'itineraries-search', data: { disable_with: t('helpers.disable_with') }
      .spinner-border.text-primary.ml-2.itineraries-spinner#itineraries-spinner-j role='status'
        span.sr-only = t('loading')

app/views/itineraries/_table.html.slim
.table-responsive
  table.table.table-itinerary
    thead
      tr
        th = Itinerary.human_attribute_name(:start_address)
        th = Itinerary.human_attribute_name(:end_address)
        th
          span.d-block.d-sm-none
            span.fas.fa-info-circle data-toggle='tooltip' title=t('itineraries.common.features')
          span.d-none.d-sm-block = t('itineraries.common.features')
        - if edit
          th = t('helpers.actions')
        - else
          th = User.model_name.human
          th = Itinerary.human_attribute_name(:leave_date)
    tbody
      - itineraries.each do |itinerary|
        tr.vertical-align-middle
          td = link_to itinerary.start_address, itinerary_path(itinerary)
          td = link_to itinerary.end_address, itinerary_path(itinerary)
          td
            .feature-icons
              - if itinerary.pink?
                span.fas.fa-lock.feature-icon.text-pink data-toggle='tooltip' title=Itinerary.human_attribute_name(:pink)
              - if itinerary.daily?
                span.fas.fa-redo.feature-icon data-toggle='tooltip' title=Itinerary.human_attribute_name(:daily)
              - if itinerary.round_trip?
                span.fas.fa-exchange-alt.feature-icon data-toggle='tooltip' title=Itinerary.human_attribute_name(:round_trip)
              - if itinerary.pets_allowed?
                span.fas.fa-paw.feature-icon data-toggle='tooltip' title=Itinerary.human_attribute_name(:pets_allowed)
              - if itinerary.smoking_allowed?
                span.fas.fa-smoking.feature-icon data-toggle='tooltip' title=Itinerary.human_attribute_name(:smoking_allowed)
          - if edit
            td
              = link_to edit_itinerary_path(itinerary), class: 'btn btn-sm btn-secondary mr-2' do
                span.fas.fa-pencil-alt<>
                = t('helpers.links.edit')
              = link_to itinerary_path(itinerary), method: :delete, data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-sm btn-danger' do
                span.fas.fa-times<>
                = t('helpers.links.destroy')
          - else
            td = link_to itinerary.user, user_path(itinerary.user)
            td = l(itinerary.leave_date.in_time_zone, format: :short)

app/views/itineraries/edit.html.slim
- title t('.title')
.container
  == render 'header'
  = simple_form_for @itinerary, validate: true, html: { class: 'form-horizontal' } do |f|
    == render 'shared/error_messages', object: f.object
    == render 'form', f: f
    .row
      .col-sm-9.offset-sm-3
        = f.button :button, class: 'btn-primary', data: { disable_with: t('helpers.disable_with') }

app/views/itineraries/index.html.slim
- title t('.title')
.container
  .row
    .col-sm-4
      h3 = yield :title
      == render 'search'
      #map-error-j.d-none-soft.alert.alert-danger
    .col-sm-8
      .embed-responsive.embed-responsive-16by9.google-maps
        .embed-responsive-item#index-itineraries-map *map_config_attributes
      #itineraries-thumbs.row

app/views/itineraries/new.html.slim
- title t('.title')
.container
  - if @itinerary.errors.any?
    .alert.alert-danger.alert-dismissable.fade.show
      button type='button' class='close' data-dismiss='alert' aria-label=t('close')
        span aria-hidden='true' &times;
      h5.alert-heading = t('errors.template.header', model: Itinerary.model_name.human, count: @itinerary.errors.size)
      = t('errors.template.body')
      ul
        - @itinerary.errors.full_messages.each do |message|
          li = message
  .row
    .col-md-6
      #wizard-step-1-title.itinerary-step.active
        h3 = t('.plan_route')
    .col-md-6
      #wizard-step-2-title.itinerary-step.d-none.d-md-block
        h3 = t('.insert_details_and_confirm')
  = simple_form_for @itinerary, validate: true do |f|
    .form-group
      #wizard-step-1-content data-step='1'
        == render 'route_step', f: f
      #wizard-step-2-content.d-none-soft data-step='2'
        .row
          .col-sm-4
            = image_tag transparent_gif_image_data, class: 'img-fluid google-static-map', id: 'itinerary-preview-image', alt: '', data: { google_maps_api_key: APP_CONFIG.google_maps_api_key }
          .col-sm-8
            h1.itinerary-title
              small = Itinerary.human_attribute_name :start_address
              span#itinerary-preview-from
              small = Itinerary.human_attribute_name :end_address
              span#itinerary-preview-to
        .form-horizontal == render 'form', f: f
    .form-group.text-center
      = f.hidden_field :route
      = f.hidden_field :via_waypoints
      = button_tag t('.previous_step'), type: 'button', class: 'btn btn-secondary d-none-soft mr-2', name: 'back_button', id: 'wizard-prev-step-button-j', disabled: true
      = f.submit t('.next_step'), type: 'button', class: 'btn btn-primary mr-2', name: 'next_button', id: 'wizard-next-step-button', disabled: false
      = f.submit t('.confirm_and_share'), class: 'btn btn-primary d-none-soft', id: 'new_itinerary_submit-j', disabled: true, data: { disable_with: t('helpers.disable_with') }

app/views/itineraries/show.html.slim
- title @itinerary.title
== render 'opengraph_head_contents', itinerary: @itinerary
.container
  == render 'shared/flash_messages'
  == render 'header'
  - if user_signed_in?
    - if current_user == @itinerary.user
      = link_to edit_itinerary_path(@itinerary), class: 'btn btn-primary' do
        span.fas.fa-pencil-alt<>
        = t('helpers.titles.edit', model: Itinerary.model_name.human)
    - else
      = link_to new_or_show_conversation_path(@conversation), class: 'btn btn-primary mr-2' do
        span.fas.fa-comment<>
        = t('.contact', user: @itinerary.user_first_name)
      /
        .btn-group
          button.btn.btn-warning
            span.fas.fa-flag<>
          button.btn.btn-warning.dropdown-toggle data-toggle='dropdown'
            span.caret
          ul.dropdown-menu role='menu'
            li= link_to t('.report_itinerary'), '#'
  - else
    = button_to user_auth0_omniauth_authorize_path, form_class: 'd-inline-block', class: 'btn btn-primary btn-lg' do
      = t('.login_to_contact')