config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'pages#home'

  resources :conversations, only: %i[show new create update index] do
    get :unread, on: :collection
  end

  resources :feedbacks, only: %i[show new create edit update destroy index]

  resources :itineraries, only: %i[show new create edit update destroy index search] do
    post :search, on: :collection
    resources :build
  end

  resources :users, only: %i[show update destroy] do
    get :itineraries, on: :member
  end

  # Admin Area
  namespace :admin do
    resources :users, only: [:index] do
      get :login_as, on: :member
      post :ban, :unban, on: :member
    end
  end

  # Root route aliases
  get :dashboard, to: 'users#dashboard'
  get :settings, to: 'users#settings'
  get :banned, to: 'users#banned'

  get :about, to: 'pages#about'
  get :how_it_works, to: 'pages#how_it_works'
  get :privacy, to: 'pages#privacy'
  get :terms, to: 'pages#terms'
  get :demo_terms, to: 'pages#demo_terms'
  post :report_uri, to: 'pages#report_uri'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Auth0Omniauthable

  # Include default devise modules. Others available are:
  devise :omniauthable, omniauth_providers: [:auth0]
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :trackable, :validatable

  GENDER = %w[male female].freeze

  paginates_per 25

  has_many :feedbacks, dependent: :nullify

  has_many :itineraries, dependent: :destroy

  has_many :conversations, ->(user) { unscope(:where).where(sender: user).or(where(receiver: user)) }, inverse_of: :sender

  validates :gender, inclusion: GENDER, allow_blank: true
  validates :time_zone, inclusion: ActiveSupport::TimeZone.all.map(&:name)
  validates :vehicle_avg_consumption, numericality: { greater_than: 0, less_than: 10 }, presence: true

  def age
    ((Time.current.to_s(:number).to_i - birthday.at_midnight.to_s(:number).to_i) / 1e10.to_i) if birthday?
  end

  def female?
    gender == 'female'
  end

  def first_name
    @first_name ||= name.split[0] if name?
  end

  def to_s
    name || id.to_s
  end

  def unread_conversations_count
    conversations.unread(self).count
  end

  def self.from_omniauth(auth_hash)
    where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create do |user|
      user.email = auth_hash.info.email
      user.image = auth_hash.info.image
      user.name  = auth_hash.info.name
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < BaseController
    before_action :set_user, only: %i[login_as ban unban]
    before_action :prevent_autoban, only: %i[ban unban]

    def index
      @users = User.order(:name).page params[:page]
    end

    def login_as
      sign_in_and_redirect :user, @user
    end

    def ban
      if @user.update(banned: true)
        redirect_to admin_users_path, flash: { success: t('flash.admin.users.success.ban') }
      else
        redirect_to admin_users_path, flash: { error: t('flash.admin.users.error.ban') }
      end
    end

    def unban
      if @user.update(banned: false)
        redirect_to admin_users_path, flash: { success: t('flash.admin.users.success.unban') }
      else
        redirect_to admin_users_path, flash: { error: t('flash.admin.users.error.unban') }
      end
    end

    private

    def set_user
      @user = User.find params[:id]
    end

    def prevent_autoban
      redirect_to admin_users_path, flash: { error: t('flash.admin.users.error.ban') } if @user == current_user
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < ::Devise::OmniauthCallbacksController
    def auth0
      @user = User.from_omniauth(auth_hash)

      if @user.persisted?
        @user.update_info_from_auth_hash! auth_hash
        sign_in_and_redirect @user, event: :authentication
      else
        redirect_to root_path, flash: { error: t('flash.sessions.error.create') }
      end
    end

    protected

    def after_omniauth_failure_path_for(_scope)
      root_path
    end

    def auth_hash
      request.env['omniauth.auth']
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user_as_current_user, only: %i[update dashboard itineraries settings]

  def show
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to :settings, flash: { success: t('flash.users.success.update') }
    else
      render :settings
    end
  end

  def destroy
    current_user.destroy
    session[:user_id] = nil
    redirect_to root_path, flash: { success: t('flash.users.success.destroy') }
  end

  def banned
    redirect_to root_path unless current_user.banned?
  end

  def dashboard
    @latest_itineraries = Itinerary.includes(:user).order(created_at: :desc).limit 10

    # Gender filter
    @latest_itineraries = @latest_itineraries.where(pink: false) unless current_user.female?
  end

  def itineraries
    @itineraries = @user.itineraries.order(created_at: :desc)
  end

  def settings; end

  private

  def set_user_as_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit :time_zone, :locale, :vehicle_avg_consumption
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def auth0_profile_picture(user, type = :square)
    if user_signed_in? && user.image?
      "#{user.image}?type=#{type}"
    else
      asset_pack_path('media/images/user.jpg')
    end
  end

  def user_profile_picture(user, size: [50, 50], type: :square, style: 'img-fluid', opts: {})
    tag :img,
        { width:  ("#{size[0]}px" if size),
          height: ("#{size[1]}px" if size),
          src:    auth0_profile_picture(user, type),
          alt:    '',
          class:  style }.merge(opts)
  end
end

app/views/users/_calculator.html.slim
.modal.d-none-soft#fuel-cost-calculator
  .modal-header
    btn.close type='button' data-dismiss='modal' &times;
    h3 Calcola consumi
  .modal-body
    = form_tag 'consumption-calculator-form', class: 'form-horizontal' do
      .control-group
        = label_tag :fuel_type, t('.fuel_type'), class: 'control-label'
        .controls
          = select_tag :fuel_type, options_for_select(%w[diesel petrol lpg methane].map { |f| [t(".fuel_#{f}"), f] })
      .control-group
        = label_tag :vehicle_type, t('.vehicle_type'), class: 'control-label'
        .controls
          = select_tag :vehicle_type, options_for_select(%w[compact standard high_consumption].map { |f| [t(".vehicle_#{f}"), f] }, selected: 'standard')
      .control-group
        = label_tag :fuel_price, t('.fuel_price'), class: 'control-label'
        .controls
          .input-append
            = text_field_tag :fuel_price, nil, class: 'input-mini text-right'
            span.add-on
              = t('.100_km')
      .control-group
        = label_tag :fuel_price, t('.fuel_price'), class: 'control-label'
        .controls
          .input-append
            = text_field_tag :fuel_price, nil, class: 'input-mini text-right'
            span.add-on
              | &euro;
              = t('.per_liter')
          p.form-text
            | Prezzi medi al 16/07/2012: Benzina: 1,758 - Diesel: 1,649 - GPL: 0,741 - Metano: 0,972
      .control-group
        .controls
          h3
            | #{t('.fuel_cost_estimate')}:
            span#fuel-cost
            span &euro; / km
  .modal-footer
    = link_to t('save'), '#', data: { dismiss: 'modal' }, id: 'save-fuel-cost', class: 'btn btn-primary'
    = link_to t('close'), '#', data: { dismiss: 'modal' }, class: 'btn'

app/views/users/banned.html.slim
- title t('.title')
.container
  .page-header.text-center
    h1.text-danger
      span.fas.fa-ban<>
      = t('.you_were_banned')
    p.lead = t('.banned_description_html')

app/views/users/dashboard.html.slim
- title t('.title')
.container
  == render 'shared/flash_messages'
  ul.nav.nav-pills.nav-fill.mt-2.mb-2
    li.nav-item
      = link_to itineraries_path do
        span.fas.fa-search<>
        = t('.search_itineraries')
    li.nav-item
      = link_to new_itinerary_path do
        span.fas.fa-plus<>
        = t('.new_itinerary')
    li.nav-item
      = link_to itineraries_user_path(current_user) do
        span.fas.fa-route<>
        = t('.your_itineraries')
  h3 = t('.latest_itineraries')
  == render 'itineraries/table', itineraries: @latest_itineraries, edit: false

app/views/users/itineraries.html.slim
- title t('.title')
.container
  == render 'shared/flash_messages'
  .page-header
    h1 = yield :title
  == render 'itineraries/table', itineraries: @itineraries, edit: true

app/views/users/settings.html.slim
- title t('.account_settings')
.container
  == render 'shared/flash_messages'

  .page-header
    h1 = yield :title
  p.lead = t('.user_profile_details')

  = simple_form_for @user, validate: true do |f|
    == render 'shared/error_messages', object: f.object

    fieldset
      legend = t('.vehicle_information')
      = f.input :vehicle_avg_consumption do
        .input-group
          = f.text_field :vehicle_avg_consumption, class: 'form-control text-right'
          .input-group-append
            span.input-group-text = "#{APP_CONFIG.fuel_currency}/km"
      p.form-text
        = t('.vehicle_avg_consumption_help')

    fieldset
      legend = t('.application_settings')
      = f.input :locale, collection: I18n.available_locales.map { |locale| [t('lang_native_name', locale: locale), locale] }, disabled: I18n.available_locales.one?
      = f.input :time_zone, include_blank: false
    fieldset
      legend = t('.send_email')
      = f.input :send_email_messages, as: :boolean
      p.form-text
        = t('.send_email_at_address')
        b< = current_user.email

    .form-group
      = f.button :button, class: 'btn btn-primary', data: { disable_with: t('helpers.disable_with') }

app/views/users/show.html.slim
- title @user
.container
  .row
    .col-sm-3.text-sm-center
      = user_profile_picture @user, size: nil, type: :large, style: 'img--user-profile'
    .col-sm-9
      h1 = @user
      p.text-muted
        small = t('.member_since', date: l(@user.created_at.to_date, format: :month_year))
      - if @user.bio?
        blockquote.user-blockquote
          p = @user.bio