config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'pages#home'

  resources :conversations, only: %i[show new create update index] do
    get :unread, on: :collection
  end

  resources :feedbacks, only: %i[show new create edit update destroy index]

  resources :itineraries, only: %i[show new create edit update destroy index search] do
    post :search, on: :collection
    resources :build
  end

  resources :users, only: %i[show update destroy] do
    get :itineraries, on: :member
  end

  # Admin Area
  namespace :admin do
    resources :users, only: [:index] do
      get :login_as, on: :member
      post :ban, :unban, on: :member
    end
  end

  # Root route aliases
  get :dashboard, to: 'users#dashboard'
  get :settings, to: 'users#settings'
  get :banned, to: 'users#banned'

  get :about, to: 'pages#about'
  get :how_it_works, to: 'pages#how_it_works'
  get :privacy, to: 'pages#privacy'
  get :terms, to: 'pages#terms'
  get :demo_terms, to: 'pages#demo_terms'
  post :report_uri, to: 'pages#report_uri'
end

app/views/shared/_advertising.html.slim
.alert.alert-info.alert--advertising.fade.show
  button type='button' class='close' data-dismiss='alert' aria-label=t('close')
    span aria-hidden='true' &times;
  h2.h5.alert-heading = t('.enterprises')
  = t('.contact_us_html')

app/views/shared/_error_messages.html.slim
- if object.errors.full_messages.any?
  .alert.alert-block.alert-danger.fade.show
    button type='button' class='close' data-dismiss='alert' aria-label=t('close')
      span aria-hidden='true' &times;
    h5 = t('helpers.form.error')
    - object.errors.full_messages.each do |msg|
      = msg
      br

app/views/shared/_flash_messages.html.slim
- flash.each do |type, message|
  .alert.fade.show class="alert-#{twitterized_type(type)}"
    = message

app/views/shared/_footer.html.slim
footer.main-footer
  .container
    ul.list-footer
      li
        = link_to 'https://diowa.com' do
          = inline_svg_pack_tag 'media/images/diowa.svg', class: 'diowa-logo', aria: true, title: 'diowa'
      - if user_signed_in?
        li = link_to t('about'), :about
        li = link_to t('how_it_works'), :how_it_works
        - unless APP_CONFIG.demo_mode
          li = link_to t('terms'), :terms
      li
        span.fab.fa-github<> aria-hidden='true'
        span.sr-only = t('.github_repository')
        = link_to 'diowa/icare', APP_CONFIG.repository_url
      - if user_signed_in?
        li
          span.fa.fa-bullhorn<> aria-hidden='true'
          = link_to Feedback.model_name.human(count: :lot), feedbacks_url
        - if APP_CONFIG.demo_mode
          li
            = link_to user_path(current_user), method: :delete, class: 'text-danger', data: { confirm: t('helpers.links.confirm') } do
              span.fa.fa-times<> aria-hidden='true'
              = t('delete_account')
    - if APP_CONFIG.demo_mode
      p.demo-app
        span.fa.fa-exclamation-triangle<> aria-hidden='true'
        = t('demo_mode')

app/views/shared/_google_tag_manager.html.slim
script async='' src="https://www.googletagmanager.com/gtag/js?id=#{APP_CONFIG.google_analytics_id}" data-turbolinks-eval='false'

javascript:
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '#{APP_CONFIG.google_analytics_id}', { 'anonymize_ip': true, 'page_path': location.pathname });

app/views/shared/_modal_why_auth0.en-US.html.slim
#why-auth0.modal.fade tabindex='-1' role='dialog' aria-labelledby=t('why_auth0') aria-hidden=true
  .modal-dialog role='document'
    .modal-content
      .modal-header
        h3.modal-title = t('why_auth0')
        button.close type='button' data-dismiss='modal' aria-label=t('close') aria-hidden=true &times;
      .modal-body
        p
          ' We want to show how it is possible to integrate this application with an existing
          | OAuth provider
      .modal-footer
        = link_to t('close'), '#', 'aria-hidden' => true, data: { dismiss: 'modal' }, class: 'btn btn-primary'

app/views/shared/_modal_why_auth0.it-IT.html.slim
#why-auth0.modal.fade tabindex='-1' role='dialog' aria-labelledby=t('why_auth0') aria-hidden=true
  .modal-dialog role='document'
    .modal-content
      .modal-header
        h3.modal-title = t('why_auth0')
        button.close type='button' data-dismiss='modal' aria-label=t('close') aria-hidden=true &times;
      .modal-body
        p
          ' Vogliamo mostrare come integrare questa applicazione con un provider
          | OAuth esistente
      .modal-footer
        = link_to t('close'), '#', 'aria-hidden' => true, data: { dismiss: 'modal' }, class: 'btn btn-primary'

app/views/shared/_navbar.html.slim
nav.navbar.main-navbar
  .container
    = link_to user_signed_in? ? :dashboard : root_path, class: 'navbar-brand' do
      = inline_svg_pack_tag 'media/images/logo.svg', aria: true, title: APP_CONFIG.app_name
      span.hidden-xs = APP_CONFIG.app_name
    button.navbar-toggler.navbar-toggler-right type='button' data-toggle='collapse' data-target='#main-navbar-collapse' aria-controls='main-navbar-collapse' aria-expanded='false' aria-label=t('.toggle_navigation')
      span.navbar-toggler-icon
    - if user_signed_in?
      == render 'shared/notifications'
      #main-navbar-collapse.collapse.navbar-collapse
        ul.navbar-nav.main-navbar-nav
          li.nav-item#navbar-user-info
            = link_to user_path(current_user), class: 'nav-link nav-link--profile' do
              = user_profile_picture current_user, size: nil, style: 'nav-link__user-image'
              span.nav-link__user-name = current_user
          li.nav-item.dropdown
            a.nav-link#main-navbar-dropdown href='#' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'
              span.fa.fa-cog aria-hidden='true'
              span.sr-only = t('.settings')
            .dropdown-menu.dropdown-menu-right aria-labelledby='main-navbar-dropdown'
              = link_to t('.account_settings'), :settings, class: 'dropdown-item'
              - if current_user.admin?
                .dropdown-divider
                = link_to t('.admin_users'), admin_users_path, class: 'dropdown-item'
              .dropdown-divider
              = link_to t('logout'), destroy_user_session_path, method: :delete, class: 'dropdown-item'
    - else
      .navbar-collapse.collapse#main-navbar-collapse role='navigation'
        ul.navbar-nav.main-navbar-nav
          li.nav-item = link_to t('how_it_works'), :how_it_works, class: 'nav-link'
          li.nav-item = link_to t('about'), :about, class: 'nav-link'
          li.nav-item.dropdown
            a.nav-link.dropdown-toggle#main-navbar-lang-dropdown href='#' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'
              span.fas.fa-globe.mr-1 aria-hidden='true'
              = t('lang_native_name')
            .dropdown-menu.dropdown-menu-right aria-labelledby='main-navbar-lang-dropdown'
              - (I18n.available_locales - [I18n.locale]).each do |locale|
                = link_to t('lang_native_name', locale: locale), url_for(locale: locale), class: 'dropdown-item'
          li.nav-item
            = button_to user_auth0_omniauth_authorize_path, form_class: 'inline-form', class: 'btn btn-primary' do
                = t('login_with_auth0')

app/views/shared/_notifications.html.slim
ul.navbar-notifications.nav.navbar-nav
  = notifications_tag :conversations, 'comments'